### ISSUE TITLE
Add version to summary report

### ISSUE THREAD

**Issue by JackUkleja** [LateGenXer/finance#4]
Nice work on the calculator. One idea is to add a version number (or even direct link to GitHub release) to the summary report for forensics. i.e. HMRC have a query about your calculations, and you need to know which version of the script logic was used (as I'm sure it will evolve). Cheers

**Comment by jrfonseca** [comment]
Sure.  I'm not doing releases (most people will consume this through the Streamlit site anyway), but I could include the URL for the GitHub commit.  I'll add it to my to do list.

**Comment by LateGenXer** [comment]
Sure. I'm not doing releases (most people will consume this through the Streamlit site anyway), but I could include the URL for the GitHub commit. I'll add it to my to do list.

**Comment by LateGenXer** [comment]
Now cgtcalc.py reports end up with something like:

```
ABOUT

Generated by cgtcalc.py version c2cfa05 (2024-11-17).
```
